default:
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  services:
  - docker:19.03.13-dind
  before_script:
  - until docker info; do sleep 1; done

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
- push

.push_globals: &push-globs
  before_script:
  - until docker info; do sleep 1; done
  - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
  - gcloud auth configure-docker -q
  - docker login -u mjg@plural.sh -p $PLURAL_ACCESS_TOKEN dkr.plural.sh

build-console:
  stage: push
  <<: *push-globs
  only:
  - master
  script:
  - make build
  - make push